fix: patch for osx build
dosfstools/dosfstools pull request #158
Opened 2021-01-31 17:44 UTC by chenrui333

```
device_info.c:27:10: fatal error: 'sys/sysmacros.h' file not found
#include <sys/sysmacros.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

relates to https://github.com/Homebrew/homebrew-core/pull/70104

2021-02-01 00:49 UTC, pali requested changes
This change cause compilation failure on Debian 10:
```
$ make
Making all in src
make[1]: Entering directory '/tmp/dosfstools/src'
gcc -DPACKAGE_NAME=\"dosfstools\" -DPACKAGE_TARNAME=\"dosfstools\" -DPACKAGE_VERSION=\"4.2\" -DPACKAGE_STRING=\"dosfstools\ 4.2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"dosfstools\" -DVERSION=\"4.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_ERR_H=1 -DHAVE_LINUX_FD_H=1 -DHAVE_LINUX_HDREG_H=1 -DHAVE_LINUX_VERSION_H=1 -DHAVE_LINUX_LOOP_H=1 -DHAVE_SYS_QUEUE_H=1 -DHAVE_ENDIAN_H=1 -DHAVE_VASPRINTF=1 -DHAVE_DECL_GETMNTENT=1 -DHAVE_DECL_GETMNTINFO=0 -DICONV_CONST= -I.  -I./blkdev  -Wall -Wextra -Wno-sign-compare -Wno-missing-field-initializers -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -W -Wall -O2 -g -fwrapv -fsanitize=address -MT testdevinfo-device_info.o -MD -MP -MF .deps/testdevinfo-device_info.Tpo -c -o testdevinfo-device_info.o `test -f 'device_info.c' || echo './'`device_info.c
device_info.c: In function 'get_block_linux_info':
device_info.c:126:11: warning: implicit declaration of function 'major' [-Wimplicit-function-declaration]
     maj = major(rdev);
           ^~~~~
device_info.c:127:11: warning: implicit declaration of function 'minor'; did you mean 'mknod'? [-Wimplicit-function-declaration]
     min = minor(rdev);
           ^~~~~
           mknod
mv -f .deps/testdevinfo-device_info.Tpo .deps/testdevinfo-device_info.Po
gcc -Wall -Wextra -Wno-sign-compare -Wno-missing-field-initializers -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -W -Wall -O2 -g -fwrapv -fsanitize=address   -o testdevinfo testdevinfo-testdevinfo.o testdevinfo-device_info.o blkdev/testdevinfo-blkdev.o blkdev/testdevinfo-linux_version.o  
/usr/bin/ld: testdevinfo-device_info.o: in function `get_block_linux_info':
/tmp/dosfstools/src/device_info.c:126: undefined reference to `major'
/usr/bin/ld: /tmp/dosfstools/src/device_info.c:127: undefined reference to `minor'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:471: testdevinfo] Error 1
make[1]: Leaving directory '/tmp/dosfstools/src'
make: *** [Makefile:412: all-recursive] Error 1
```

2021-02-02 00:27 UTC, pali commented
Prior applying any such changes in dosfstools project, I would like to know, have you tested that it is actually working on OS X?What is the output of `./src/testdevinfo` utility of some disk, e.g. `/dev/disk1s1` on OS X? And what is the output of same disk, but from the Linux system with Linux version of `./src/testdevinfo`?

2021-02-05 01:55 UTC, i0ntempest commented
> Prior applying any such changes in dosfstools project, I would like to know, have you tested that it is actually working on OS X?What is the output of `./src/testdevinfo` utility of some disk, e.g. `/dev/disk1s1` on OS X? And what is the output of same disk, but from the Linux system with Linux version of `./src/testdevinfo`?

I tried compiling 4.2 with this patch and also 4.1, for both versions `./src/testdevinfo /dev/disk0s1` (my ESP) gives a bunch of unknowns except for sector size and size. On my Raspberry Pi I can get all the info. But fsck seems to work regardless.

2021-02-05 09:03 UTC, pali commented
And can you provide output from `./src/testdevinfo` tests? Ideally with reporting a new issue for fixing this code.

2021-02-14 00:48 UTC, Neustradamus commented
@i0ntempest: Have you seen last @pali comment?

2021-02-14 01:05 UTC, i0ntempest commented
> @i0ntempest: Have you seen last @pali comment?

Sorry I somehow missed that. I don’t have my Mac right now and I’ll need a few days before I get home. Will open a new issue with required outputs when I do.

2021-02-14 02:25 UTC, chenrui333 commented
I can provide the outs on my mojave machine, one sec.

2021-02-14 02:33 UTC, chenrui333 commented
I actually don't see `./src/testdevinfo`?
```
$ ls -1 /usr/local/Cellar/dosfstools/4.2/sbin/
dosfsck
dosfslabel
fatlabel
fsck.fat
fsck.msdos
fsck.vfat
mkdosfs
mkfs.fat
mkfs.msdos
mkfs.vfat
```

2021-02-14 03:05 UTC, i0ntempest commented
> I actually don't see `./src/testdevinfo`?
> 
> ```
> $ ls -1 /usr/local/Cellar/dosfstools/4.2/sbin/
> dosfsck
> dosfslabel
> fatlabel
> fsck.fat
> fsck.msdos
> fsck.vfat
> mkdosfs
> mkfs.fat
> mkfs.msdos
> mkfs.vfat
> ```

testdevinfo is a test binary that is not installed, only available after manually building the code.

2021-02-21 12:58 UTC, pali commented
Please rebase this pull request on top of the master branch.

2021-04-25 21:25 UTC, pali commented
Hello! Would you rebase & fix this pull request? Or is not this an issue anymore? (I do not have such OS so I cannot verify it)

2021-08-19 21:34 UTC, pali commented
ping

2021-08-20 13:53 UTC, i0ntempest commented
#166

2021-08-20 14:54 UTC, closed without merging