DOC(fatlabel.8.in): minor spelling typos
dosfstools/dosfstools pull request #173
Opened 2022-01-21 19:12 UTC by liketechnik

Fixes #145

2022-02-01 19:11 UTC, elkablo requested changes

2022-02-01 19:11 UTC, elkablo commented on manpages/fatlabel.8.in
> +fatlabel \- sets or get MS-DOS filesystem label or volume ID
Looking at other man pages, for example `man ls` or `man diff`, they use first person / root form:
* `ls - list directory contents`
* `diff - compare files line by line`

so I would leave this as `set`.

2022-02-22 22:19 UTC, pali commented
@liketechnik could you please fix above issue?

2022-02-26 09:29 UTC, liketechnik commented
@pali I reverted the relevant change back. In case you prefer to have the change of this PR in a single commit, I'll happily squash the commits together.

2022-02-26 13:05 UTC, pali commented
Please squash commits and rebase on top of the master branch.

2022-02-28 17:49 UTC, liketechnik commented
@pali done.

2022-02-28 18:41 UTC, merged